// angular/crud-angular/frontend/src/app/views/home/home.component.ts
import { HeaderService } from './../../components/template/header/header.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  
  
  constructor(private headerService: HeaderService) {
    headerService.headerData = {
      title: "Início",
      icon: 'home',
      routeUrl: ''
    }
  }

  ngOnInit(): void {
  }

}

<mat-card class="home mat-elevations-z3">
    <mat-card-title class="title">
        Welcome!
    </mat-card-title>
    <mat-card-subtitle class="subtitle">
        Sistema para exemplificar a construção de um cadastro em Angular
    </mat-card-subtitle>
</mat-card>

// react/crud-react/frontend/src/components/home/Home.jsx
import React from 'react';
import Main from '../templates/Main';


export default props =>
    <Main icon='home' title='Início' subtitle='Projeto Crud de React' >
        <div className="display-4">Bem Vindo</div>
        <hr />
        <p className="mb-0">Sistema para exemplificar a construção de um cadastro, desenvolvido em React!</p>
    </Main>
