// svelte/svelte-calculadora/src/App.svelte
<script lang="ts">
import Calculadora from "./components/Calculadora.svelte";


</script>

<main>
    <Calculadora/>
</main>

<style>
    :global(body) {
        background-color: black;
    }

    :root {
        --cor-fundo: #555;
    }

	main {
		display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
	}
</style>

// vue/calculator/src/App.vue
<template>
    <div id="app">
        <h1>Calculadora</h1>
        <Calculator />
    </div>
</template>


<script>
import Calculator from "./main/Calculator"


export default {
    components: {Calculator}
}
</script>


<style>
@font-face {
    font-family: "RobotoMono";
    src: url("./fonts/RobotoMono-Thin.ttf");
}

* {
    font-family: "RobotoMono", monospace;
}

body {
    margin: 0;
}


#app {
    display: flex;
    flex-direction: column;
    height: 100vh;
    justify-content: center;
    align-items: center;
    text-align: center;
    color: white;
    background: linear-gradient(to right, rgb(83, 105, 118), rgb(41, 46, 73));
}
</style>
